### ISSUE TITLE
[Enhancement] Unnatural and confusing counting of comments

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#159]
I explained it in the picture.

![marking as unread](https://user-images.githubusercontent.com/2397851/27098881-5192c012-5079-11e7-9402-3383abcfb075.png)

**Comment by revilheart** [comment]
All posts are not unread on the first discussion, or at least hey aren't supposed to be. All discussions should count the number of comments plus the OP. So if all comments were unread in the first discussion, it would be +87.

Same with the second discussion. All comments are unread, since it counts +85, 84 comments plus OP. Is the OP really read in this one? There appears to be something wrong with your count then. I still can't reproduce the wrong count issue here.

**Comment by gizellos** [comment]
I see. I think the problem is that the system how you count it is totally confusing and unnatural. One would expect that the OP is either included in both the numbers or it is not included in both the numbers. I think that when the OP is not included in the first number, it should't be also in the second number in the brackets.

For example 77 (+78) logically means that there is 77 comments and you haven't read 78 of them which is nonsens.

**Comment by gizellos** [comment]
I could say it also like this: the first number is supposed to be total amount and the other in the brackets a part of it. Therefore the other number cannot be higher. That's how people naturally feel it. It is like that in all other cases with a number and another number in brackets.

**Comment by ldeman** [comment]
i think it's just because that first '77' (in this example) is vanilla and left alone untouched by the script.  tbh i'd prefer that part stay vanilla, otherwise it would confuse me to see a '1' on it when there isn't any actual comments. 

i'd be fine if it just didn't count the op as "read" or "unread" personally though.

in fact another relative suggestion i didn't quite know how to approach that i'd like to see would be...
have the marking of the op be attached to the threads being faded out or not as if they were visited.  that could be the identifier of the op itself being read.  then it could also be used to unread the op so that it could essentially reset that thread to look like it had never been touched.  

say for instance i open a thread and notice it's a train thread and i'm out of points.  i could highlight it, but then i'd end up with a massive highlight list.   i could browser bookmark it, but then i might forget about it.  or... i could just unread & unfade it as if it had never been touched by unmarking the op as read.

**Comment by gizellos** [comment]
> i think it's just because that first '77' (in this example) is vanilla and left alone untouched by the script.

Yes, I think so too.

**Comment by ldeman** [comment]
in fact, interesting related side note...

the marking of the op thread button seems to no longer be there. (since one of the last 2 updates.)

**Comment by revilheart** [comment]
OP is no longer counted and you can now unmark discussions as visited, but I did not attach the OP to it because it doesn't make much sense to me.

**Comment by ldeman** [comment]
the unvisited works just as well.  thanks for that.  ^^
