### ISSUE TITLE
[Enhancement] Missing tooltips in user profiles

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#178]
These two icons don't have tooltips. To tell the truth I even don't know what the icons are for, because of it. :)

![missing tooltips](https://user-images.githubusercontent.com/2397851/27286748-8d8ba570-5501-11e7-85c4-79383352c321.png)

**Comment by ldeman** [comment]
the first one is shared groups checker, but i haven't a clue on the eye icon and am rather curious to know what feature i'm lacking.

**Comment by gizellos** [comment]
Thanks. My guess about the other is hiding user's post, but I am not sure.

**Comment by ldeman** [comment]
ahh "User Filters".  yes, it is that.  (temporarily enabled the feature to see the icon)

**Comment by gizellos** [comment]
Yeah, you are right. That's a nice feature.

**Comment by gizellos** [comment]
Do you have an idea why would someone know the groups in common?

**Comment by ldeman** [comment]
i suggested it so i can tell if the people winning giveaways are still within one of the groups that the giveaways were created for. 

it comes in handy mostly for unlucky7 group where it's very frequent that someone is kicked out after their 8th win, but doesn't sync steamgifs up and tries to make off with an extra few wins.  if it ends and they were no longer in the group at the time of it ending, it's valid grounds for re-roll without permission (only the kick with time screenshot is needed).  i have to check those giveaways especially harder since it tends to happen rather frequently with that group.

**Comment by gizellos** [comment]
Thanks. It's a legit reason, indeed. Just maybe it would be better if there was a button in the winners page and it would check if the user is still there.

**Comment by ldeman** [comment]
the auto-send feature does that actually as well, however i still prefer manually combing those over because another portion of the rules for that group is to maintain a +7 gift difference.  if i find a gifter below that difference, i'm supposed to hold the gift and request them to either fix the difference before delivery or seek permission for a re-roll.

really that group could use it's own specific script to keep it in line tbh. ^^
but this script still cuts the workload down tremendously.

**Comment by revilheart** [comment]
Pretty sure I could extend the option in the sender:

- Only send to users who are still members of at least one of the groups for group giveaways with a gift difference higher than [text input to enter the value].

**Comment by ldeman** [comment]
that would be amazing.  i can't think of any other rules that would prevent me from being able to go fully automated if that were in place.  =)

**Comment by revilheart** [comment]
They now have tooltips.
