### ISSUE TITLE
[Enhancement] Show points for each Entered GA on Entered page

### ISSUE THREAD

**Issue by Ack0** [revilheart/ESGST#193]
Would be useful if each entered GA had their points shown on Entered page, like this: 
![image](https://user-images.githubusercontent.com/7303084/27517573-4ba89bce-59a5-11e7-8841-2191d774fdea.png)

**Comment by ldeman** [comment]
+1 except add more details then just points (level, type, etc / see screenshots) & also function on created/won pages.  i'm using a script already that does this, but would prefer it be a part of ESGST anyways.

example shots=

entered:
![____entered_](https://user-images.githubusercontent.com/10275898/27517998-819e4012-599b-11e7-8970-aca3249823e0.png)

created:
![__created__](https://user-images.githubusercontent.com/10275898/27518003-8ee8cd14-599b-11e7-8d9b-b334561062a4.png)

won:
![___won__](https://user-images.githubusercontent.com/10275898/27518005-97abd7fc-599b-11e7-84e8-8970af79d012.png)

**Comment by gizellos** [comment]
+1

**Comment by Ack0** [comment]
> i'm using a script already that does this

@ldeman can you share the link to this one? Thanks.

**Comment by ldeman** [comment]
i see the message was deleted, but i don't think revilheart would mind still so here's the link to the current script i'm using.

https://www.steamgifts.com/discussion/CHaNe/userscript-shows-more-info-at-giveaways-entered-created-won-pages

=)

**Comment by revilheart** [comment]
Added

**Comment by Ack0** [comment]
@revilheart isn't working here. Can you confirm that is working with v6.Beta.14.0?

**Comment by ldeman** [comment]
@Ack0 it's working for me.  did you enable "Created/Entered/Won Giveaway Details" in the ESGST settings menu?

**Comment by Ack0** [comment]
@ldeman Yes, it's enabled. I got this error on console, I just don't know if it will be useful:

```
08:32:41.188 VM2051:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Window.getCewgdDetail (eval at E_c (:3:221), <anonymous>:21491:35)
    at <anonymous>:2:398
    at e.string.f.function.c.(anonymous function) (eval at exec_fn (:1:108), <anonymous>:54:325)
```

**Comment by gizellos** [comment]
I either wrote it to a different issue or I deleted it accidentally. Therefore sorry if it is still here:

There is Type Everyone. I think the word Public would be better there. It would make more sense because everyone is more like an answer to "who can enter" than a type of giveaway.

**Comment by ldeman** [comment]
@gizellos you put it inside itad data request #194 -- i was confused when i saw it there, but now it makes sense.  ;)

**Comment by ldeman** [comment]
@Ack0 ahh, okay.  just leave that console error up and revil will know what it means.  =)

**Comment by gizellos** [comment]
@Ideman Hehe, thanks. I deleted that one. :)

**Comment by revilheart** [comment]
@gizellos Yeah, I wasn't sure which to use, because I know people are used to "public" and "private", but those words aren't a part of SG. so I went with "everyone" and "invite only". But "public" does make more sense than "everyone" in terms of type. I think I'll leave "invite only" though, because that makes sense as well. You could say "this is an invite only giveaway", but you can't say "this is an everyone giveaway".

**Comment by Ack0** [comment]
@revilheart it's working now with v6.Beta.14.1. Thanks!

This script[1] show Points way faster than ESGST. I don't know the magic, but can you improve this later? Thanks again.

[1] https://greasyfork.org/scripts/23859-sg-entered-created-won-giveaway-page/

**Comment by ldeman** [comment]
i was actually curious about performance as well, wondering if maybe ruphine had found a way to get information without that many requests, cause the other script is rather fast at pulling information.  i understand it's request limited, but it seems excessively slow on that page imo compared to even the [groups](https://www.steamgifts.com/account/steam/groups) differences being requested.

**Comment by revilheart** [comment]
@Ack0 If I'm looking at that script correctly, it's really bad for SG because it has no limits between requests as far as I know. So no, I can't make it that fast because that puts too much load on the SG server.

@ldeman  Does it run faster if you disable Game Categories? Because Game Categories also needs to request stuff, so the requests would have to be balanced between Game Categories and this feature and it would indeed be a bit slow.

**Comment by ldeman** [comment]
@revilheart yes, with categories disabled it runs almost 3x faster.  right on par with the other script.

**Comment by revilheart** [comment]
@ldeman Hmm actually Game Categories doesn't use the limit because it requests to Steam, so there might be something else that's causing the 2 features to conflict. I'll look into it.

**Comment by revilheart** [comment]
But I don't think it's really that important, since the details only need to be requested once, so every other time you open the page they should load a lot faster. And also I plan on implementing some observers later that will save the details upon creating/entering giveaways, so that it doesn't even need to make any requests for future giveaways.

**Comment by ldeman** [comment]
ahh okay, yeah.  it was just loading fast the second time due to them being cached.  i see now after testing on other pages with and without the categories it doesn't seem to make much of a difference.  sounds great though on the future observers.  ^^

**Comment by revilheart** [comment]
I think I can still make it a bit faster though, will try something later.

**Comment by ldeman** [comment]
sounds great =)
