### ISSUE TITLE
[Enhancement] moving source link in Decrypted giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#210]
The link to the source in Decrypted giveaways doesn't look natural on SG. It could be moved beside the time remaining.

![source link](https://user-images.githubusercontent.com/2397851/27743138-4d58b6ce-5dbb-11e7-8864-5da39d1af51d.png)

**Comment by revilheart** [comment]
Done. I moved it to before the remaining time though, because it looked better for me. Hope that's ok.

**Comment by gizellos** [comment]
Good but please switch the order of time and the link. The time should be always first because the time is always there.

![2017-07-13_214344](https://user-images.githubusercontent.com/2397851/28184682-a0057cdc-6814-11e7-983d-a70dc09239a0.png)

**Comment by revilheart** [comment]
The source should always be there as well for encrypted giveaways added since the version where the source link was implemented. I'll have to look into this, there might be a bug, but I don't really like putting the source link after the time, it feels very odd, especially for users that have Accurate Timestamps enabled. It's way easier to click on it if it comes first.

**Comment by gizellos** [comment]
I believe that the bug is caused when I don't click on the star at the top of the page after I post a GA with an encrypted GA. But Maybe I am wrong.
