### ISSUE TITLE
[Enhancement] Don't allow to create duplicate giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#214]
Awww, I just had to delete 5 of my giveaways because I created them twice. I used giveaway creator and I thought that the button View Giveaways is something like preview, so I clicked on it, checked the giveaways and then clicked on Create giveaways.

Please don't allow to create duplicate giveaways. Check if the giveaways wasn't already created and don't allow to execute the Create giveaways function in case they were (in case they have the same product key). And I maybe you could rename the View giveaways button somehow. It is quite confusing now.

**Comment by gizellos** [comment]
Maybe the vagons should be deleted after creating the giveaways. Or is there a reason for them to be there even after the creation?

**Comment by ldeman** [comment]
hmm... i'm starting to think this issue and the "create giveaway button not working" are linked together issues.  from my understanding steamgifts doesn't allow recreation of the same key unless the other giveaways that had the key used in it were already ended.  those times when it was not allowing the button to work were probably times the key being placed in the field was already a live going giveaway, and that's why it wasn't creating them. 

it would at least explain why it's intermittently working and not working at times.

**Comment by ldeman** [comment]
also, giveaways need to be able to be recreated anyways.  "0entries, recreate"  ^^

**Comment by revilheart** [comment]
They're not the same button, though. "View Giveaways" button only appears after the creation process is done, so why would someone click "Create Giveaways" wait until all giveaways are created, then click on "View Giveaways" and click on "Create Giveaways" again?

**Comment by gizellos** [comment]
It's seems I wrote it badly. It's seems I clicked on Create Giveaways twice. But it is a trap, anyway. The script should not create giveaways again from the green created giveaways. It should make create them only from white or red giveaways, shouldn't it?

**Comment by revilheart** [comment]
Done, clicking the button again should not recreate green giveaways.

**Comment by gizellos** [comment]
Coolio. Thanks.
