### ISSUE TITLE
[Bug(s)] few things i noticed that seem broken

### ISSUE THREAD

**Issue by ldeman** [revilheart/ESGST#234]
few things i've noticed that have been broken with some of the latest updates:  (most already reported, but trying to make it easier to track)

1: [Confirmed Fixed 16.2] not received / muti-win checker doesn't seem to end after coming back with the results, it continues on checking nobody with "...".

2: [testing with 3 copy freshly created 1hr GA for confirmation] winner inbox highlighter hasn't functioned for the latest couple days of winners.  (unsent gift sender)

3. [Confirmed Fixed 16.2] (also reported by pilda) - the changelog is no longer appearing with that feature enabled.

4. [Confirmed Fixed 16.3] changelog dates are off for the latest couple updates.

**Comment by ldeman** [comment]
correction, winner inbox highlighter does work with manually sent giveaways.  i had just used the unsent gift sender more then i had thought on most of them.

**Comment by ldeman** [comment]
5.  auto-remove entries upon sync -- also broken

**Comment by gizellos** [comment]
> 2: winner inbox highlighter hasn't functioned for the latest couple days of winners. (seems both unsent gift sender, and manually sent gifts both are not highlighting the winners thanks)

What do you mean by the highlight? Just the cup? It works well for me.

![2017-07-13_181005](https://user-images.githubusercontent.com/2397851/28176111-843d80c6-67f6-11e7-9873-55448c9898a5.png)

**Comment by ldeman** [comment]
@gizellos it works/worked fine on manually sent gifts, but the auto-gift sender sent ones weren't having the cup next to them on their ty comments. 

i'm unsure if that one was fixed with the 16.2 update, but several others are.

@revilheart ill edit in "[Confirmed Fixed]" next to each of the numbers as i verify they work for me.  ;)

**Comment by gizellos** [comment]
> auto-gift sender sent ones weren't having the...

I use only the auto-gift sender and without problems. It seems to be a specific issue for your settings/setup.

BTW I am not sure if the cup should be called "highlighter". When I hear the word highlighter, I imagine something  like a different background color. I believe there is a better word for it. Maybe marker?

**Comment by revilheart** [comment]
Pretty sure if it started happening in 16 or 16.1 (I don't remember), it should be fixed in 16.2. There was a major bug that was saving all data to the settings storage once and then using that outdated data for everything.

**Comment by ldeman** [comment]
sounds great, it did seem a little sporadic in working before so that would explain it best really.  one minute i thought it wasn't functioning on any of them (manually sent or auto sent) and then suddenly it was working for some of them (a few known manually sent).

**Comment by revilheart** [comment]
@gizellos I agree. I've always used the word "highlighter" because when I first started the script there was a script called Whitelist/Blacklist Indicator and I had a feature that did the same thing, so I didn't want them to have the same name and called mine Whitelist/Blacklist Highlighter. Although nowadays that name does fit, because of the new option that allows you to color whitelisted/blacklisted users. But for other features it does seem odd. I think "indicator" is better than "marker", I'm not sure.

**Comment by gizellos** [comment]
Yes, Indicator is definitively better than marker, you are right. :)

**Comment by ldeman** [comment]
yeah, indicator or even to match the "Use icons instead of colors." you could somehow fit in icon in the name. "Winner Comment Identifier / Icon"

**Comment by revilheart** [comment]
Coming up with feature names is so hard. xD Sometimes I wish I would just stop that and write actual descriptions instead of their names, like I do with the options, for example:

Whitelist/Blacklist Highlighter -> Highlight/indicate whitelisted/blacklisted users.
Inbox Winners Highlighter -> Indicate comments from giveaway winners in the inbox page.

I feel like doing that would remove the need for a tooltip for most of the features.

**Comment by ldeman** [comment]
#2 [Confirmed Bugged Still] Unsent Gift Sender - Winner Comment Highlighter (or whatever it's called if it changed) is still confirmed to not highlight winners.  or at least not in all instances.  11mins old sent thru auto-sender, thank you message came in 4mins ago, and it's not highlighted.

**Comment by ldeman** [comment]
well.. maybe it does work.. at least that user/comment is now highlighted.  but it didn't work on the first load.

**Comment by revilheart** [comment]
Unsent Gifts Sender should be fixed, let me know if not.
