### ISSUE TITLE
[Enhancement] Improve the "Ratings" filter for giveaways

### ISSUE THREAD

**Issue by grimmute** [revilheart/ESGST#236]
Can you add the rating icon in the giveaway box, instead of under the game name? 

Can it also show the review rating and the total number of reviews next to the icon without us having to hover on the icon?

Thanks a lot for your hardwork

**Comment by revilheart** [comment]
Do you mean in Grid View? I don't like that, as someone else might want the wishlist icon to appear in the giveaway box as well, for example, and then someone else might want the trading cards icon to appear. The categories work better under the game name because there are too many of them. If you want to just see giveaways from a specific rating range, you can use Giveaway Filters.

Adding the text next to the icon is doable, yes.

**Comment by grimmute** [comment]
I aggree with you partly. But this way there is a huge empty line under the game's name which I think looks pretty bad. I was saying maybe you can place it on the empty space next to the timer. I marked it on the picture.

![rating icon](https://user-images.githubusercontent.com/25132481/28186516-1c3750fa-6824-11e7-894b-f43e92ea22be.JPG)

**Comment by revilheart** [comment]
Ah, I thought you were talking about Grid View by "giveaway box". But still, the script injects other features in that area as well, so it wouldn't look good. What version are you on? Because I recently changed the categories to appear in front of the name so there isn't that white space below it.

**Comment by grimmute** [comment]
I'm on v6.Beta.16.5. It still looks like on the picture to me. I only have the Ratings filter enabled.

**Comment by revilheart** [comment]
Do you have simplified version enabled?

**Comment by grimmute** [comment]
Ah, I didn't know it was doing that! Now it's next to the name like you said. :)

Thank you for your hard work.

**Comment by revilheart** [comment]
Added an option to show it next to the icon in 16.6.
