### ISSUE TITLE
Counter doesn't show in the first and last wagon in trains

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#240]
I used this description:
`[ESGST-P]Previous[/ESGST-P] ([ESGST-C]/[/ESGST-C]) [ESGST-N]Next[/ESGST-N]`

It worked well, except the first and the last wagons. There, it didn't show the counter at all. 

So instead of _(1/45) Next_ it showed just _Next_

I have a suggestion: show also plain text Previous in the first wagon and Next in the last one. It would be better.

So it would look like this:
Previous (1/45) [Next](www.example.com)

**Comment by gizellos** [comment]
![2017-07-14_213959](https://user-images.githubusercontent.com/2397851/28228051-0c887558-68dd-11e7-9b8f-894b0544a52a.png)

**Comment by gizellos** [comment]
And this is the last one. 
![2017-07-14_214125](https://user-images.githubusercontent.com/2397851/28228101-4c257bd4-68dd-11e7-870f-e172562a0a7e.png)

**Comment by revilheart** [comment]
That's because that's not the correct use of the formatting. Separators are not shown in the first and last wagons because there is no previous/next link from them. I'll see what I can do to make this format acceptable.

**Comment by revilheart** [comment]
I also don't see how showing previous in plain text makes any sense.

**Comment by gizellos** [comment]
> That's because that's not the correct use of the formatting.

Why? It worked in the other wagons.

> I also don't see how showing previous in plain text makes any sense.

It looks better than without it. It is quite normal thing.

**Comment by revilheart** [comment]
Because of what I just said, separators are not shown in the first and last wagons. Imagine the following format:

[ESGST-P]Previous[/ESGST-P] | [ESGST-N]Next[/ESGST-N]

Would it make sense to show " | Next" in the first wagon? No, it would make sense to show only "Next", so the separators are removed from the first and last wagons.

I have to disagree. It makes me think that something went wrong and there was a previous/next giveaway that wasn't connected properly.

**Comment by gizellos** [comment]
Dude, you have never seen this concept on some other webpages? It is really a very common thing and all people understand that. It is not confusing because it is logical that when you are on something that is first, the previous word is not a link because it doesn't exist. And the reason why it looks better is the the format is the same as on the other pages. 

To tell the truth, the first thing that got to my head when I opened the first wagon was, that something went wrong. Not just there were not the previous word, but there also were not the counter. I was really quite frightened that all the wagons will contain just one word.

> Because of what I just said, separators are not shown in the first and last wagons.
I think you were talking about the format of the counter because the counter was not there too. 

I enclosed a comparision. You really think the first picture is better? It looks quite bad with the counter at the beginning. IMO it looks much better on the second example.

![inactive link](https://user-images.githubusercontent.com/2397851/28230137-0554fcee-68e6-11e7-9ef4-1a0d0679ca55.png)

**Comment by gizellos** [comment]
Or the missing counter in the first and last wagon is also on purpose?

**Comment by revilheart** [comment]
> Dude, you have never seen this concept on some other webpages? It is really a very common thing and all people understand that. It is not confusing because it is logical that when you are on something that is first, the previous word is not a link because it doesn't exist. And the reason why it looks better is the the format is the same as on the other pages.

Nope, never. Something being common doesn't mean it's good. And you shouldn't assume "all" people understand that. I don't, so it's not "all" people. It makes 0 logic to me, but I can an option for it in the script, there's no problem.

> I enclosed a comparision. You really think the first picture is better? It looks quite bad with the counter at the beginning. IMO it looks much better on the second example.

Yes, first picture is much better than the second to me, because there's no useless previous text. But if we're talking about the counter, both pictures look bad to me. The counter makes much more sense at the end of both links for me, like "Previous Next (1/45)". Or above/below it.

> Or the missing counter in the first and last wagon is also on purpose?

That's what I keep trying to explain to you, the separators are not shown in the first and last wagons because there are no previous/next links in them. And in the format you used, you put the counter between the two links, which made it the separator, therefore it is not shown in the first and last wagons.

**Comment by gizellos** [comment]
OK I see now. Then, make it as an option, please. :)

**Comment by revilheart** [comment]
Done

**Comment by gizellos** [comment]
You are fast. Thanks a lot. :)

**Comment by revilheart** [comment]
It was something very easy to do, really. :)
