### ISSUE TITLE
Support for bump link in trains

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#248]
I would love to have a bump link in every wagon. It would be fine because if someone needed to leave the train before its end and wanted to bump it, they could use t he bump link even before the end of the train.

I am aware that it is quite a hard task since the script cannot know the URL of the discussion before the discussion exists.

I have been thinking about it since you implement the train creator and i got an idea.

1. in the train creator, there would be all the inputs for making the topic for the train
2. one could either type all the stuff there each time they make a new train or use a template for it (in fact, the templates for the topic would be another good feature)
3. before the script starts to create the giveaways, it will make the thread and close it
4. the script will use the URL for the bump links
5. the script will edit the thread and put the link to the first wagon there (it would replace something like [ESGST-FW] - FW means first wagon)

I know its solution is not optimal but I was not able to find a better way.

**Comment by revilheart** [comment]
A better way, I think:

1. A new button is added before "Create" called "Add Discussion".
2. When clicking on "Add Discussion", a new discussion tab is open and a new button is added after "Create Discussion" called "Add".
3. When clicking on "Add", the discussion is created and immediately closed.
4. The new discussion tab is then closed and you are returned to the new giveaway tab.
5. The "Add Discussion" button is now removed from the new giveaway tab and a text appears somewhere saying "Discussion added.", linking to the added discussion.

I don't see the point of topic templates, because there's nothing in topics that would remain the same: title changes, description changes, polls change, category can change, etc...

**Comment by gizellos** [comment]
Sound good. :)

For trains the templates would be really pointless, you are right. 

But generally, it could be quite useful, because there could be same tags for generating text. For example, you would make some giveaways with Create Multiple Giveaways and you would use a template with a tag that will be replaced by a list of the created giveaways,  encrypted giveaways or rachart table.  Or people such as youtubers or streamers would have the links to their channels. :)

**Comment by revilheart** [comment]
Still pointless, though, as that only applies to the description of the discussions. I think what you want is that feature you suggested before, "user-defined replies".

**Comment by gizellos** [comment]
Well, yes - the "user-defined replies" could do the same work. :)

**Comment by gizellos** [comment]
I can use the Search & Replace function from Giveaways Tools for it now. I think it is good enough and you can close this suggestion if you agree.

**Comment by revilheart** [comment]
I still think it would be nice to have this feature though. Would save the need to go to the created page and select the giveaways.

**Comment by gizellos** [comment]
Yeah, it would be nice.  Then keep it open. I am looking forward to it. :)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Cool, thanks a lot. I will try it as soon as possible. :)
