### ISSUE TITLE
RaChart enhancement - Owned with alt accounts

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#280]
This is my last wish from [this closed issue.](https://github.com/revilheart/ESGST/issues/39)

I would like to see if I own the games in RaChart tables with my alt steam account(s).

I have just one account so I don't care how many accounts would support it but someone may be like to support more of them.

**Comment by revilheart** [comment]
Ok, how would it work? The same way as it currently works (just "Owned"), or with details about which account owns it? Like, "Owned by X".

**Comment by revilheart** [comment]
And do you want an option to make it work only with discussion tables?

**Comment by gizellos** [comment]
> Ok, how would it work?

I am not sure about this but either way it should be easily visible (without the need of waiting for a help text or something like that). Maybe similarly like now - instead of Owned, there would be the  Owned by X. 

Or maybe just Owned as it is now but we could set different color for each the alt. So we would have just to remember which account has which color (I think this is quite simple and elegant solution). It's on you. 


> And do you want an option to make it work only with discussion tables (instead of everywhere)?

Yes. It wouldn't much sense elsewhere.

**Comment by revilheart** [comment]
It will be just an extension to the owned tag in Game Categories, so it will be visually the same as it is now.

>> Yes. It wouldn't much sense elsewhere.

Well, I'm sure other people would disagree. I personally want to know if I own a game anywhere on SG (I don't use SG's option to hide owned games because I don't like hiding stuff). The default behavior will be everywhere just like all the other tags, I just wanted to know if an additional option to enable it only for tables would be necessary.

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Nice, thanks. :)
