### ISSUE TITLE
Redundant Manage link in the Settings

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#289]
I think the link should not be there since. BTW I think that the word "ESGST Settings" would be much better.  The word Manage is quite confusing because it is normally used for some specific features and not for general settings. ...or I would remove it completely (that's in fact what I would prefer the most), since the button for settings is on every page (ESGST menu).

I already wrote you about it once, though. I just still have a problem with it each time I see it. :)

![2017-07-25_172629](https://user-images.githubusercontent.com/2397851/28580086-cd8a6f84-715e-11e7-9309-c6a723e01fb6.png)

**Comment by revilheart** [comment]
It's still faster to click on "Manage" than to close the popup and then click on the ESGST button, though, so I'd like to keep it.

And I know you already wrote about it once, but "ESGST Settings" is just too big of a text. I believe "Manage" fits better, because you can manage data/settings, etc... But if you know that it goes to the settings menu, why the confusion? :P

**Comment by revilheart** [comment]
Changed it to "Settings".
