### ISSUE TITLE
ESGST - Hidden Featured Container is extremely slow

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#334]
The Hidden Featured Container has been extremely slow last a few versions.  It was OK before. I made a test and compared it with element hider in adblock (it is uBlock in my case).

ESGST video:
![esgst - hidden featured container](https://user-images.githubusercontent.com/2397851/29240336-7e75d006-7f63-11e7-8709-e28b37d249f6.gif)

uBlock video:
![ublock - hidden featured container](https://user-images.githubusercontent.com/2397851/29240351-a4fff83c-7f63-11e7-879b-888d184d9db2.gif)

**Comment by gizellos** [comment]
Before the speed was similar to the speed of the ublock.

**Comment by revilheart** [comment]
It looks perfectly normal to me. The script has always taken about 5 seconds to load on the main page for me.

**Comment by gizellos** [comment]
Are you joking? It was as fast as in the second video until now. I don't lie to you. It tooks just a small fraction of second until now. Not it takes several seconds and it is not normal at all.

**Comment by revilheart** [comment]
No, I'm not joking, the script is slow. So yes, it's completely normal, as far as I can tell. I don't see how the script could have loaded in a fraction of a second before in the main page, as there are a lot of features that need to be loaded for the main page. And may I also remind you that you have Old Active Discussions Design enabled, which already slows down the page by a lot and is not constant.

I didn't say you were lying, but your GIFs don't tell me anything. There are multiple factors that can influence how fast a page is loaded. Have you intensively tested to make sure you are correct? Have you tried loading the page multiple times to see if it's always the same speed? And have you tested with Hidden Featured Container disabled (and no uBlock) to make sure the slowdown really is caused by the feature? You show me a GIF with the feature enabled and a GIF with uBlock enabled, but where is the GIF with both disabled?

**Comment by gizellos** [comment]
The problem is that it started to work so slowly after one update and the speed of the script didn't change with the update. The speed seems to be the same as far as I can tell. I didn't use a stopwatch, though. 

I think the speed of the script should not be a deal for hiding an element. Hiding elements i so fast, that it should not wait for any other actions of the script. So maybe the problem is that it waits for something? 

I just installed an older version of ESGST (v6.Beta.20.0) on Vivaldi browser (it use the same core as Chrome) and made a comparison. You can see there the difference. The version could be much newer, though. It is just a few version ago when this started to be so slowly.

The page works normally when I disable both the uBlock and the hidding feature. The speed when I try to reload the page seems to be the same. Maybe it is a bit faster but it would be just a few percent but it would have to be faster several times to be like before.

![hidden featured container - new vs old](https://user-images.githubusercontent.com/2397851/29249400-51b8928e-802f-11e7-9df9-8c0b08253ac0.gif)

**Comment by gizellos** [comment]
Here is a gif with disabled both the feature and uBlock hiding. 
![disabled hide featured container](https://user-images.githubusercontent.com/2397851/29249423-c3be7218-802f-11e7-86c3-c464c4723c47.gif)

**Comment by revilheart** [comment]
The Vivaldi comparison is still invalid because:

* You don't have your data on the Vivaldi version, and large data can slow loading time.
* You don't have Old Active Discussions Design enabled in the Vivaldi version.

And in your GIF with both disabled it takes the same time as with the feature enabled, so it cannot be related to this feature.

Have you checked how large your storage is?
