### ISSUE TITLE
Stuck while retrieving giveaway data

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#53]
When I try to get the data from [this user](https://www.steamgifts.com/user/MetalFreak), it will never end. It always stuck on page 3.

I got some errors after the profile loading and 1 when I was trying to get the data.
![2017-03-10_205317](https://cloud.githubusercontent.com/assets/2397851/23810861/a3771108-05d3-11e7-9e13-6c29513d76b4.png)

**Comment by gizellos** [comment]
BTW could you please show also _total pages_ in the scanning info?

**Comment by revilheart** [comment]
It's because that user gave away a Humble bundle when you could do that on SG and so that giveaway doesn't have a Steam ID. I'll fix it in the next version.

Whitelist / Blacklist Checker does not show that information though, as it's impossible to know the last page of giveaways. It only shows "page x...", just like User Giveaways Data.

**Comment by gizellos** [comment]
What about using math? Something like Total giveaways / 50? It should work, shouldn't it? You would have to round it somehow.

**Comment by ldeman** [comment]
it's this # divided by 25 
![image](https://cloud.githubusercontent.com/assets/10275898/23823068/d541e720-061f-11e7-9f8a-5288082615e4.png) rounded up by one page.

**Comment by revilheart** [comment]
Hmm I thought the count took into account multiple copies, which wouldn't make the result accurate, but looks like the Giveaways and Gifts Sent numbers are different. That might work.

**Comment by revilheart** [comment]
Re-opening for the total page suggestion, which I had forgotten.

**Comment by revilheart** [comment]
Checkers now show the last page.
