### ISSUE TITLE
[Enhancement] Show how many GAs were removed

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#80]
I am talking about the feature "Remove entries for owned games". When it ends it will write just  "Entries removed." - no matter if there was something removed or not. I would like to know exact number of  the removed entries. Please show it.

**Comment by ldeman** [comment]
+1  i'm tired of scrolling to the bottom of the page to see how many total entered before and after.

**Comment by gizellos** [comment]
There could be overally more result messages in the script. For example, when I check to counter whitelists, I won't get a message about the number of countered whitelists as well. When I enter all WL giveaways, the place where the GAs were is empty instead of a message like "No giveaways".

**Comment by rafaelgs18** [comment]
Well, for whitelists you can just see the users under "You are whitelisted by:" and those are all the users that were whitelisted back (highlighted users would indicate that they were probably whitelisted for the first time), so I don't see how that message would be necessary.

Writing "No giveaways." if all the giveaways in the page are hidden might be a bit complicated, but I'll see if I can add that. Still find it a bit unnecessary, because if the list is empty you can conclude that you entered all giveaways or there are none.

I'll improve the Entries Remover results and also include the name of the games that were removed later.

**Comment by gizellos** [comment]
If the list is empty, my conclusion is that the data was not loaded because of a bug or connection problems.  That's how all the other apps works. It's unwritten rule to show an info if there are not any results. It makes sense and it is an useful thing. ;)

**Comment by rafaelgs18** [comment]
The problem is this is not a regular case, since the giveaways are there, but hidden. I don't see how a bug / connection problem would prevent them from appearing since they are loaded by SG with the page. But I think I found a simple way to show a message. :)

**Comment by revilheart** [comment]
Re-opening for the "No giveaways." message.

**Comment by revilheart** [comment]
You should now see a filtered count in the pagination of each page. If all giveaways are filtered, it will show, for example, "Displaying 1 to 25 (25 filtered)".
